---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "name" . | indent 1 }}
  labels:
    app.kubernetes.io/name: nginx-app
    app.kubernetes.io/instance: nginx
{{- end }}
